name: pop_pop_win
author: Dart Team <misc@dartlang.org>
description: '"Pop, Pop, Win!" is an implementation of Minesweeper in Dart.'
homepage: https://github.com/dart-lang/sample-pop_pop_win
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  stagexl: '^0.13.1'
  stack_trace: '^1.6.8'
dev_dependencies:
  browser: '^0.10.0'
  dart_to_js_script_rewriter: ^1.0.0
  test: '^0.12.0'
transformers:
- $dart2js:
    commandLineOptions: [--dump-info, --no-frequency-based-minification]
- dart_to_js_script_rewriter
dependency_overrides:
  stagexl:
    git: https://github.com/bp74/StageXL